// M36: a parked gate per measured wall in the Apple sweep. Every test here is `#[ignore]`d ON
// PURPOSE, and each reason is the measurement that parks it — the label the sweep printed, the
// exit codes, the recorder-pid regime, the recorder's own RECORD ERROR / panic line with the
// symbol, the landmark, the committed evidence file, the charter class, and what un-parks it.
// The sweep's old category string ("replay diverged") is not evidence and appears in no reason.
//
// Each body is the statement that becomes true when its wall falls: the binary records to a
// clean exit and replays bit-for-bit. The assertion messages print the recorder's stderr tail so
// a run with `--ignored` shows the wall by name (that run is this file's positive control).
mod util;

fn records_and_replays_clean(path: &str) {
    if !std::path::Path::new(path).exists() {
        eprintln!("SKIPPED: {path} is not present on this machine");
        return;
    }
    let (rec, trace) = util::record_dynamic(path);
    let tail = rec.stderr.lines().rev().take(4).collect::<Vec<_>>().into_iter().rev().collect::<Vec<_>>().join("\n");
    assert_eq!(rec.code, 0, "{path}: record exited {} — the wall this gate is parked at, in the recorder's own words:\n{tail}", rec.code);
    let rp = util::replay(&trace);
    assert_eq!(rp.code, 0, "{path}: replay exited {}: {}", rp.code, rp.stderr.lines().last().unwrap_or(""));
    assert_eq!(rp.stdout, rec.stdout, "{path}: replay stdout differs from the recording");
}

#[test]
#[ignore = "M36 wall, class B (known-unmodelled), route M37. /bin/csh: runs O/L/I recpids 73617/1013/17386 (O and I colliding, L non-colliding), identical in all three: label `recorder panicked: thread 'main' (31774615) panicked at crates/retrace-core/src/lib.rs:1140:17: dup2 is not modelled by the M10 fd table (unexercised by any gate guest); implement target-slot allocation before a guest uses it` (the M33 fail-loud assert on an unmodelled dup2; the thread id is 31850265 in L and 31894566 in I, and is the only thing that varies), rc=101, no replay ran, no landmark. The pid regime changes the self-pid ESRCH count in the kept trace (5/0/5) but not the wall: the trace reaches dup2 either way (Finding 4). Evidence docs/sweep-evidence/2026-09-13-m36/csh.{O,L,I}.rec.err. UN-IGNORE when the fd table models dup2 (M10's unmodelled-but-fail-loud entry)."]
fn csh_records_and_replays() { records_and_replays_clean("/bin/csh"); }

#[test]
#[ignore = "M36 wall, class B (known-unmodelled), route M37. /bin/tcsh: runs O/L/I recpids 74616/2044/18480 (O and I colliding, L non-colliding), identical in all three: label `recorder panicked: thread 'main' (31780397) panicked at crates/retrace-core/src/lib.rs:1140:17: dup2 is not modelled by the M10 fd table (unexercised by any gate guest); implement target-slot allocation before a guest uses it` (the M33 fail-loud assert on an unmodelled dup2; the thread id is 31856621 in L and 31900825 in I, and is the only thing that varies), rc=101, no replay ran, no landmark. The pid regime changes the self-pid ESRCH count in the kept trace (5/0/5) but not the wall: the trace reaches dup2 either way (Finding 4). Evidence docs/sweep-evidence/2026-09-13-m36/tcsh.{O,L,I}.rec.err. UN-IGNORE when the fd table models dup2 (M10's unmodelled-but-fail-loud entry)."]
fn tcsh_records_and_replays() { records_and_replays_clean("/bin/tcsh"); }

#[test]
#[ignore = "M36 wall, class B then C; the B wall routes to M37, the C wall is parked, not routed. /bin/launchctl: colliding recorder pids (run O recpid 74012, run I recpid 17867) → label `record error, rc=4: RECORD ERROR: non-syscall exit: exception (EC=0x3c ISS=0x1 FSC=0x1) far/ipa=0x0 (UNMAPPED) pc=0x18035f084 elr=0x1804af110`, rc/rp 4/3, landmark 331/325: `brk #1` in libdispatch `_firehose_task_buffer_init+0x12c` (elr = libsystem_kernel `__proc_info+8`) after the guest's own `proc_info(2, pid, 17)` was answered ESRCH — M34 §4b forwards a recorder pid that is a mapped IPA as a host pointer (11 self-pid ESRCH in the kept trace; the window is [0x4000,0x18000), Finding 1). Non-colliding pid (run L recpid 1415) → `record error, rc=4: RECORD ERROR: unsupported mach_msg2 at pc 0x1804adc34: options 0x404000102: message-queue send without the send+rcv RPC shape`, rc/rp 4/3, landmark 338, 0 ESRCH: the RCV-shaped message-queue call, `Route::Unsupported` (pc = `mach_msg2_trap+8`), class C. Which face a run shows depends only on the recorder's pid. Evidence docs/sweep-evidence/2026-09-13-m36/launchctl.{O,L,I}.{rec,rp}.err. UN-IGNORE when §4b is fixed (M37) AND the box services the RCV-shaped message-queue call."]
fn launchctl_records_and_replays() { records_and_replays_clean("/bin/launchctl"); }

#[test]
#[ignore = "M36 wall, class B then C; the B wall routes to M37, the C wall is parked, not routed. /usr/bin/automationmodetool: colliding recorder pids (run O recpid 74786, run I recpid 18664) → label `record error, rc=4: RECORD ERROR: non-syscall exit: exception (EC=0x3c ISS=0x1 FSC=0x1) far/ipa=0x0 (UNMAPPED) pc=0x18035f084 elr=0x1804af110`, rc/rp 4/3, landmark 334/334: `brk #1` in libdispatch `_firehose_task_buffer_init+0x12c` (elr = libsystem_kernel `__proc_info+8`) after the guest's own `proc_info(2, pid, 17)` was answered ESRCH — M34 §4b forwards a recorder pid that is a mapped IPA as a host pointer (11 self-pid ESRCH in the kept trace; the window is [0x4000,0x18000), Finding 1). Non-colliding pid (run L recpid 2223) → `record error, rc=4: RECORD ERROR: unsupported mach_msg2 at pc 0x1804adc34: options 0x404000102: message-queue send without the send+rcv RPC shape`, rc/rp 4/3, landmark 339, 0 ESRCH: the RCV-shaped message-queue call, `Route::Unsupported` (pc = `mach_msg2_trap+8`), class C. Which face a run shows depends only on the recorder's pid. Evidence docs/sweep-evidence/2026-09-13-m36/automationmodetool.{O,L,I}.{rec,rp}.err. UN-IGNORE when §4b is fixed (M37) AND the box services the RCV-shaped message-queue call."]
fn automationmodetool_records_and_replays() { records_and_replays_clean("/usr/bin/automationmodetool"); }

#[test]
#[ignore = "M36 wall, class B then C; the B wall routes to M37, the C wall is parked, not routed. /usr/bin/desdp: colliding recorder pids (run O recpid 74818, run I recpid 18693) → label `record error, rc=4: RECORD ERROR: non-syscall exit: exception (EC=0x3c ISS=0x1 FSC=0x1) far/ipa=0x0 (UNMAPPED) pc=0x18035f084 elr=0x1804af110`, rc/rp 4/3, landmark 361/361: `brk #1` in libdispatch `_firehose_task_buffer_init+0x12c` (elr = libsystem_kernel `__proc_info+8`) after the guest's own `proc_info(2, pid, 17)` was answered ESRCH — M34 §4b forwards a recorder pid that is a mapped IPA as a host pointer (11 self-pid ESRCH in the kept trace; the window is [0x4000,0x18000), Finding 1). Non-colliding pid (run L recpid 2252) → `record error, rc=4: RECORD ERROR: unsupported mach_msg2 at pc 0x1804adc34: options 0x404000102: message-queue send without the send+rcv RPC shape`, rc/rp 4/3, landmark 367, 0 ESRCH: the RCV-shaped message-queue call, `Route::Unsupported` (pc = `mach_msg2_trap+8`), class C. Which face a run shows depends only on the recorder's pid. Evidence docs/sweep-evidence/2026-09-13-m36/desdp.{O,L,I}.{rec,rp}.err. UN-IGNORE when §4b is fixed (M37) AND the box services the RCV-shaped message-queue call."]
fn desdp_records_and_replays() { records_and_replays_clean("/usr/bin/desdp"); }

#[test]
#[ignore = "M36 wall, class B then C; the B wall routes to M37, the C wall is parked, not routed. /usr/bin/dyld_info: colliding recorder pids (run O recpid 74847, run I recpid 18724) → label `record error, rc=4: RECORD ERROR: non-syscall exit: exception (EC=0x3c ISS=0x1 FSC=0x1) far/ipa=0x0 (UNMAPPED) pc=0x18035f084 elr=0x1804af110`, rc/rp 4/3, landmark 371/356: `brk #1` in libdispatch `_firehose_task_buffer_init+0x12c` (elr = libsystem_kernel `__proc_info+8`) after the guest's own `proc_info(2, pid, 17)` was answered ESRCH — M34 §4b forwards a recorder pid that is a mapped IPA as a host pointer (11 self-pid ESRCH in the kept trace; the window is [0x4000,0x18000), Finding 1). Non-colliding pid (run L recpid 2281) → `record error, rc=4: RECORD ERROR: unsupported mach_msg2 at pc 0x1804adc34: options 0x404000102: message-queue send without the send+rcv RPC shape`, rc/rp 4/3, landmark 368, 0 ESRCH: the RCV-shaped message-queue call, `Route::Unsupported` (pc = `mach_msg2_trap+8`), class C. Which face a run shows depends only on the recorder's pid. Evidence docs/sweep-evidence/2026-09-13-m36/dyld_info.{O,L,I}.{rec,rp}.err. UN-IGNORE when §4b is fixed (M37) AND the box services the RCV-shaped message-queue call."]
fn dyld_info_records_and_replays() { records_and_replays_clean("/usr/bin/dyld_info"); }

#[test]
#[ignore = "M36 wall, class B then C; the B wall routes to M37, the C wall is parked, not routed. /usr/bin/flex: colliding recorder pids (run O recpid 74877, run I recpid 18752) → label `record error, rc=4: RECORD ERROR: non-syscall exit: exception (EC=0x3c ISS=0x1 FSC=0x1) far/ipa=0x0 (UNMAPPED) pc=0x18035f084 elr=0x1804af110`, rc/rp 4/3, landmark 359/362: `brk #1` in libdispatch `_firehose_task_buffer_init+0x12c` (elr = libsystem_kernel `__proc_info+8`) after the guest's own `proc_info(2, pid, 17)` was answered ESRCH — M34 §4b forwards a recorder pid that is a mapped IPA as a host pointer (11 self-pid ESRCH in the kept trace; the window is [0x4000,0x18000), Finding 1). Non-colliding pid (run L recpid 2310) → `record error, rc=4: RECORD ERROR: unsupported mach_msg2 at pc 0x1804adc34: options 0x404000102: message-queue send without the send+rcv RPC shape`, rc/rp 4/3, landmark 370, 0 ESRCH: the RCV-shaped message-queue call, `Route::Unsupported` (pc = `mach_msg2_trap+8`), class C. Which face a run shows depends only on the recorder's pid. Evidence docs/sweep-evidence/2026-09-13-m36/flex.{O,L,I}.{rec,rp}.err. UN-IGNORE when §4b is fixed (M37) AND the box services the RCV-shaped message-queue call."]
fn flex_records_and_replays() { records_and_replays_clean("/usr/bin/flex"); }

#[test]
#[ignore = "M36 wall, class B then C; the B wall routes to M37, the C wall is parked, not routed. /usr/bin/dddiagnose: colliding recorder pid (run O recpid 74909) → label `record error, rc=4: RECORD ERROR: non-syscall exit: exception (EC=0x3c ISS=0x1 FSC=0x1) far/ipa=0x0 (UNMAPPED) pc=0x18035f084 elr=0x1804af110`, rc/rp 4/3, landmark 379: `brk #1` in libdispatch `_firehose_task_buffer_init+0x12c` (elr = libsystem_kernel `__proc_info+8`) after the guest's own `proc_info(2, pid, 17)` was answered ESRCH — M34 §4b forwards a recorder pid that is a mapped IPA as a host pointer (12 self-pid ESRCH in the kept trace, M35's signature exactly; the window is [0x4000,0x18000), Finding 1). Colliding recorder pid (run I recpid 18781) → `PASS (identical fault, rc=139)`, rc/rp 139/139: record and replay both crash at pc=0x180302eb0 (libsystem_malloc `mfm_alloc+0x230`) far=0x2000050050 esr=0x92000045 after 11 self-pid ESRCH of the same kind — §4b's second downstream face, not a pass (spec §3a); why an in-range run takes the crash rather than the brk is open (Finding 3). Non-colliding pid (run L recpid 2340) → `record error, rc=4: RECORD ERROR: unsupported mach_msg2 at pc 0x1804adc34: options 0x404000102: message-queue send without the send+rcv RPC shape`, rc/rp 4/3, landmark 379, 0 ESRCH: the RCV-shaped message-queue call, `Route::Unsupported` (pc = `mach_msg2_trap+8`), class C. Which face a run shows depends only on the recorder's pid. Evidence docs/sweep-evidence/2026-09-13-m36/dddiagnose.{O,L,I}.{rec,rp}.err. UN-IGNORE when §4b is fixed (M37) AND the box services the RCV-shaped message-queue call."]
fn dddiagnose_records_and_replays() { records_and_replays_clean("/usr/bin/dddiagnose"); }
